In [1]:
from openpyxl import Workbook
wb = Workbook()
# get default worksheet
ws = wb.active

In [2]:
# Create sheets
ws1 = wb.create_sheet("Mysheet") # insert at the end (default)

ws2 = wb.create_sheet("Mysheet", 0) # insert at first position

ws3 = wb.create_sheet("Mysheet", -1) # insert at the penultimate position

ws.title = "New Title"

for sheet in wb:
    print(sheet.title)

Mysheet1
New Title
Mysheet2
Mysheet

In [3]:
# asignar valores a celdas
ws['A4'] = 4

ten = ws.cell(row=4, column=3, value=10)

ten.value = 10.00
# obtener valores
c = ws['A4']

In [4]:
# acceder a un rango de celdas
cell_range = ws['A1':'C2']

# acceder columnas o celdas especificas
colC = ws['C']
col_range = ws['C:D']
row10 = ws[10]
row_range = ws[5:10]

In [5]:
ws

In [6]:
# obtener valores
ws.values

In [7]:
for row in ws.values:
    for value in row:
        print(value)
    print()

None
None
None
None

None
None
None
None

None
None
None
None

4
None
10.0
None

None
None
None
None

None
None
None
None

None
None
None
None

None
None
None
None

None
None
None
None

None
None
None
None

In [8]:
for row in ws.iter_rows(min_row=1, max_col=4, max_row=4, values_only=True):
...   print(row)
wb.save('balances.xlsx')

(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(4, None, 10.0, None)

In [9]:
 from openpyxl import load_workbook
wb2 = load_workbook('balances.xlsx')
wb2.sheetnames

['Mysheet1', 'New Title', 'Mysheet2', 'Mysheet']

In [10]:
ws1 = wb2.active
for row in range(1, 40):
    ws1.append(range(30))

In [13]:
from openpyxl.utils import get_column_letter
ws3 = wb2.create_sheet(title="Data")

for row in range(10, 20):
    for col in range(27, 54):
        _ = ws3.cell(column=col, row=row, value=get_column_letter(col))
        
wb2.save(filename = 'balances2.xlsx')

In [15]:
import pandas as pd

In [20]:
pd.DataFrame(ws3.values)

,0,1,2,3,4,5,6,7,8,9,...,43,44,45,46,47,48,49,50,51,52
0,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
5,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
6,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
7,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
8,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
9,None,None,None,None,None,None,None,None,None,None,...,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA
10,None,None,None,None,None,None,None,None,None,None,...,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA
11,None,None,None,None,None,None,None,None,None,None,...,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA
12,None,None,None,None,None,None,None,None,None,None,...,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA
13,None,None,None,None,None,None,None,None,None,None,...,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA
14,None,None,None,None,None,None,None,None,None,None,...,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA
15,None,None,None,None,None,None,None,None,None,None,...,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA
16,None,None,None,None,None,None,None,None,None,None,...,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA
17,None,None,None,None,None,None,None,None,None,None,...,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA
18,None,None,None,None,None,None,None,None,None,None,...,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA

In [23]:
from itertools import islice
data = ws3.values
cols = next(data)[1:]
data = list(data)
idx = [r[0] for r in data]
data = (islice(r, 1, None) for r in data)
df = pd.DataFrame(data, index=idx, columns=cols)
df

,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
NaN,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
NaN,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
NaN,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
NaN,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
NaN,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
NaN,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
NaN,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
NaN,None,None,None,None,None,None,None,None,None,None,...,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA
NaN,None,None,None,None,None,None,None,None,None,None,...,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA
NaN,None,None,None,None,None,None,None,None,None,None,...,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA
NaN,None,None,None,None,None,None,None,None,None,None,...,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA
NaN,None,None,None,None,None,None,None,None,None,None,...,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA
NaN,None,None,None,None,None,None,None,None,None,None,...,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA
NaN,None,None,None,None,None,None,None,None,None,None,...,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA
NaN,None,None,None,None,None,None,None,None,None,None,...,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA
NaN,None,None,None,None,None,None,None,None,None,None,...,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA
NaN,None,None,None,None,None,None,None,None,None,None,...,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA

In [30]:
cell_range = ws['AA10':'BA19']
cell_range

((<Cell 'New Title'.AA10>,
  <Cell 'New Title'.AB10>,
  <Cell 'New Title'.AC10>,
  <Cell 'New Title'.AD10>,
  <Cell 'New Title'.AE10>,
  <Cell 'New Title'.AF10>,
  <Cell 'New Title'.AG10>,
  <Cell 'New Title'.AH10>,
  <Cell 'New Title'.AI10>,
  <Cell 'New Title'.AJ10>,
  <Cell 'New Title'.AK10>,
  <Cell 'New Title'.AL10>,
  <Cell 'New Title'.AM10>,
  <Cell 'New Title'.AN10>,
  <Cell 'New Title'.AO10>,
  <Cell 'New Title'.AP10>,
  <Cell 'New Title'.AQ10>,
  <Cell 'New Title'.AR10>,
  <Cell 'New Title'.AS10>,
  <Cell 'New Title'.AT10>,
  <Cell 'New Title'.AU10>,
  <Cell 'New Title'.AV10>,
  <Cell 'New Title'.AW10>,
  <Cell 'New Title'.AX10>,
  <Cell 'New Title'.AY10>,
  <Cell 'New Title'.AZ10>,
  <Cell 'New Title'.BA10>),
 (<Cell 'New Title'.AA11>,
  <Cell 'New Title'.AB11>,
  <Cell 'New Title'.AC11>,
  <Cell 'New Title'.AD11>,
  <Cell 'New Title'.AE11>,
  <Cell 'New Title'.AF11>,
  <Cell 'New Title'.AG11>,
  <Cell 'New Title'.AH11>,
  <Cell 'New Title'.AI11>,
  <Cell 'New Title'.AJ11>,
  <Cell 'New Title'.AK11>,
  <Cell 'New Title'.AL11>,
  <Cell 'New Title'.AM11>,
  <Cell 'New Title'.AN11>,
  <Cell 'New Title'.AO11>,
  <Cell 'New Title'.AP11>,
  <Cell 'New Title'.AQ11>,
  <Cell 'New Title'.AR11>,
  <Cell 'New Title'.AS11>,
  <Cell 'New Title'.AT11>,
  <Cell 'New Title'.AU11>,
  <Cell 'New Title'.AV11>,
  <Cell 'New Title'.AW11>,
  <Cell 'New Title'.AX11>,
  <Cell 'New Title'.AY11>,
  <Cell 'New Title'.AZ11>,
  <Cell 'New Title'.BA11>),
 (<Cell 'New Title'.AA12>,
  <Cell 'New Title'.AB12>,
  <Cell 'New Title'.AC12>,
  <Cell 'New Title'.AD12>,
  <Cell 'New Title'.AE12>,
  <Cell 'New Title'.AF12>,
  <Cell 'New Title'.AG12>,
  <Cell 'New Title'.AH12>,
  <Cell 'New Title'.AI12>,
  <Cell 'New Title'.AJ12>,
  <Cell 'New Title'.AK12>,
  <Cell 'New Title'.AL12>,
  <Cell 'New Title'.AM12>,
  <Cell 'New Title'.AN12>,
  <Cell 'New Title'.AO12>,
  <Cell 'New Title'.AP12>,
  <Cell 'New Title'.AQ12>,
  <Cell 'New Title'.AR12>,
  <Cell 'New Title'.AS12>,
  <Cell 'New Title'.AT12>,
  <Cell 'New Title'.AU12>,
  <Cell 'New Title'.AV12>,
  <Cell 'New Title'.AW12>,
  <Cell 'New Title'.AX12>,
  <Cell 'New Title'.AY12>,
  <Cell 'New Title'.AZ12>,
  <Cell 'New Title'.BA12>),
 (<Cell 'New Title'.AA13>,
  <Cell 'New Title'.AB13>,
  <Cell 'New Title'.AC13>,
  <Cell 'New Title'.AD13>,
  <Cell 'New Title'.AE13>,
  <Cell 'New Title'.AF13>,
  <Cell 'New Title'.AG13>,
  <Cell 'New Title'.AH13>,
  <Cell 'New Title'.AI13>,
  <Cell 'New Title'.AJ13>,
  <Cell 'New Title'.AK13>,
  <Cell 'New Title'.AL13>,
  <Cell 'New Title'.AM13>,
  <Cell 'New Title'.AN13>,
  <Cell 'New Title'.AO13>,
  <Cell 'New Title'.AP13>,
  <Cell 'New Title'.AQ13>,
  <Cell 'New Title'.AR13>,
  <Cell 'New Title'.AS13>,
  <Cell 'New Title'.AT13>,
  <Cell 'New Title'.AU13>,
  <Cell 'New Title'.AV13>,
  <Cell 'New Title'.AW13>,
  <Cell 'New Title'.AX13>,
  <Cell 'New Title'.AY13>,
  <Cell 'New Title'.AZ13>,
  <Cell 'New Title'.BA13>),
 (<Cell 'New Title'.AA14>,
  <Cell 'New Title'.AB14>,
  <Cell 'New Title'.AC14>,
  <Cell 'New Title'.AD14>,
  <Cell 'New Title'.AE14>,
  <Cell 'New Title'.AF14>,
  <Cell 'New Title'.AG14>,
  <Cell 'New Title'.AH14>,
  <Cell 'New Title'.AI14>,
  <Cell 'New Title'.AJ14>,
  <Cell 'New Title'.AK14>,
  <Cell 'New Title'.AL14>,
  <Cell 'New Title'.AM14>,
  <Cell 'New Title'.AN14>,
  <Cell 'New Title'.AO14>,
  <Cell 'New Title'.AP14>,
  <Cell 'New Title'.AQ14>,
  <Cell 'New Title'.AR14>,
  <Cell 'New Title'.AS14>,
  <Cell 'New Title'.AT14>,
  <Cell 'New Title'.AU14>,
  <Cell 'New Title'.AV14>,
  <Cell 'New Title'.AW14>,
  <Cell 'New Title'.AX14>,
  <Cell 'New Title'.AY14>,
  <Cell 'New Title'.AZ14>,
  <Cell 'New Title'.BA14>),
 (<Cell 'New Title'.AA15>,
  <Cell 'New Title'.AB15>,
  <Cell 'New Title'.AC15>,
  <Cell 'New Title'.AD15>,
  <Cell 'New Title'.AE15>,
  <Cell 'New Title'.AF15>,
  <Cell 'New Title'.AG15>,
  <Cell 'New Title'.AH15>,
  <Cell 'New Title'.AI15>,
  <Cell 'New Title'.AJ15>,
  <Cell 'New Title'.AK15>,
  <Cell 'New Title'.AL15>,
  <Cell 'New Title'.AM15>,
  <Cell 'New Title'.AN15>,
  <Cell 'New Title'.AO15>,
  <Cell 'New Title'.AP15>,
  <Cell 'New Title'.AQ15>,
  <Cell 'New Title'.AR15>,
  <Cell 'New Title'.AS15>,
  <Cell 'New Title'.AT15>,
  <Cell 'New Title'.AU15>,
  <Cell 'New Title'.AV15>,
  <Cell 'New Title'.AW15>,
  <Cell 'New Title'.AX15>,
  <Cell 'New Title'.AY15>,
  <Cell 'New Title'.AZ15>,
  <Cell 'New Title'.BA15>),
 (<Cell 'New Title'.AA16>,
  <Cell 'New Title'.AB16>,
  <Cell 'New Title'.AC16>,
  <Cell 'New Title'.AD16>,
  <Cell 'New Title'.AE16>,
  <Cell 'New Title'.AF16>,
  <Cell 'New Title'.AG16>,
  <Cell 'New Title'.AH16>,
  <Cell 'New Title'.AI16>,
  <Cell 'New Title'.AJ16>,
  <Cell 'New Title'.AK16>,
  <Cell 'New Title'.AL16>,
  <Cell 'New Title'.AM16>,
  <Cell 'New Title'.AN16>,
  <Cell 'New Title'.AO16>,
  <Cell 'New Title'.AP16>,
  <Cell 'New Title'.AQ16>,
  <Cell 'New Title'.AR16>,
  <Cell 'New Title'.AS16>,
  <Cell 'New Title'.AT16>,
  <Cell 'New Title'.AU16>,
  <Cell 'New Title'.AV16>,
  <Cell 'New Title'.AW16>,
  <Cell 'New Title'.AX16>,
  <Cell 'New Title'.AY16>,
  <Cell 'New Title'.AZ16>,
  <Cell 'New Title'.BA16>),
 (<Cell 'New Title'.AA17>,
  <Cell 'New Title'.AB17>,
  <Cell 'New Title'.AC17>,
  <Cell 'New Title'.AD17>,
  <Cell 'New Title'.AE17>,
  <Cell 'New Title'.AF17>,
  <Cell 'New Title'.AG17>,
  <Cell 'New Title'.AH17>,
  <Cell 'New Title'.AI17>,
  <Cell 'New Title'.AJ17>,
  <Cell 'New Title'.AK17>,
  <Cell 'New Title'.AL17>,
  <Cell 'New Title'.AM17>,
  <Cell 'New Title'.AN17>,
  <Cell 'New Title'.AO17>,
  <Cell 'New Title'.AP17>,
  <Cell 'New Title'.AQ17>,
  <Cell 'New Title'.AR17>,
  <Cell 'New Title'.AS17>,
  <Cell 'New Title'.AT17>,
  <Cell 'New Title'.AU17>,
  <Cell 'New Title'.AV17>,
  <Cell 'New Title'.AW17>,
  <Cell 'New Title'.AX17>,
  <Cell 'New Title'.AY17>,
  <Cell 'New Title'.AZ17>,
  <Cell 'New Title'.BA17>),
 (<Cell 'New Title'.AA18>,
  <Cell 'New Title'.AB18>,
  <Cell 'New Title'.AC18>,
  <Cell 'New Title'.AD18>,
  <Cell 'New Title'.AE18>,
  <Cell 'New Title'.AF18>,
  <Cell 'New Title'.AG18>,
  <Cell 'New Title'.AH18>,
  <Cell 'New Title'.AI18>,
  <Cell 'New Title'.AJ18>,
  <Cell 'New Title'.AK18>,
  <Cell 'New Title'.AL18>,
  <Cell 'New Title'.AM18>,
  <Cell 'New Title'.AN18>,
  <Cell 'New Title'.AO18>,
  <Cell 'New Title'.AP18>,
  <Cell 'New Title'.AQ18>,
  <Cell 'New Title'.AR18>,
  <Cell 'New Title'.AS18>,
  <Cell 'New Title'.AT18>,
  <Cell 'New Title'.AU18>,
  <Cell 'New Title'.AV18>,
  <Cell 'New Title'.AW18>,
  <Cell 'New Title'.AX18>,
  <Cell 'New Title'.AY18>,
  <Cell 'New Title'.AZ18>,
  <Cell 'New Title'.BA18>),
 (<Cell 'New Title'.AA19>,
  <Cell 'New Title'.AB19>,
  <Cell 'New Title'.AC19>,
  <Cell 'New Title'.AD19>,
  <Cell 'New Title'.AE19>,
  <Cell 'New Title'.AF19>,
  <Cell 'New Title'.AG19>,
  <Cell 'New Title'.AH19>,
  <Cell 'New Title'.AI19>,
  <Cell 'New Title'.AJ19>,
  <Cell 'New Title'.AK19>,
  <Cell 'New Title'.AL19>,
  <Cell 'New Title'.AM19>,
  <Cell 'New Title'.AN19>,
  <Cell 'New Title'.AO19>,
  <Cell 'New Title'.AP19>,
  <Cell 'New Title'.AQ19>,
  <Cell 'New Title'.AR19>,
  <Cell 'New Title'.AS19>,
  <Cell 'New Title'.AT19>,
  <Cell 'New Title'.AU19>,
  <Cell 'New Title'.AV19>,
  <Cell 'New Title'.AW19>,
  <Cell 'New Title'.AX19>,
  <Cell 'New Title'.AY19>,
  <Cell 'New Title'.AZ19>,
  <Cell 'New Title'.BA19>))

In [31]:
pd.DataFrame(cell_range)

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,26
0,<Cell 'New Title'.AA10>,<Cell 'New Title'.AB10>,<Cell 'New Title'.AC10>,<Cell 'New Title'.AD10>,<Cell 'New Title'.AE10>,<Cell 'New Title'.AF10>,<Cell 'New Title'.AG10>,<Cell 'New Title'.AH10>,<Cell 'New Title'.AI10>,<Cell 'New Title'.AJ10>,...,<Cell 'New Title'.AR10>,<Cell 'New Title'.AS10>,<Cell 'New Title'.AT10>,<Cell 'New Title'.AU10>,<Cell 'New Title'.AV10>,<Cell 'New Title'.AW10>,<Cell 'New Title'.AX10>,<Cell 'New Title'.AY10>,<Cell 'New Title'.AZ10>,<Cell 'New Title'.BA10>
1,<Cell 'New Title'.AA11>,<Cell 'New Title'.AB11>,<Cell 'New Title'.AC11>,<Cell 'New Title'.AD11>,<Cell 'New Title'.AE11>,<Cell 'New Title'.AF11>,<Cell 'New Title'.AG11>,<Cell 'New Title'.AH11>,<Cell 'New Title'.AI11>,<Cell 'New Title'.AJ11>,...,<Cell 'New Title'.AR11>,<Cell 'New Title'.AS11>,<Cell 'New Title'.AT11>,<Cell 'New Title'.AU11>,<Cell 'New Title'.AV11>,<Cell 'New Title'.AW11>,<Cell 'New Title'.AX11>,<Cell 'New Title'.AY11>,<Cell 'New Title'.AZ11>,<Cell 'New Title'.BA11>
2,<Cell 'New Title'.AA12>,<Cell 'New Title'.AB12>,<Cell 'New Title'.AC12>,<Cell 'New Title'.AD12>,<Cell 'New Title'.AE12>,<Cell 'New Title'.AF12>,<Cell 'New Title'.AG12>,<Cell 'New Title'.AH12>,<Cell 'New Title'.AI12>,<Cell 'New Title'.AJ12>,...,<Cell 'New Title'.AR12>,<Cell 'New Title'.AS12>,<Cell 'New Title'.AT12>,<Cell 'New Title'.AU12>,<Cell 'New Title'.AV12>,<Cell 'New Title'.AW12>,<Cell 'New Title'.AX12>,<Cell 'New Title'.AY12>,<Cell 'New Title'.AZ12>,<Cell 'New Title'.BA12>
3,<Cell 'New Title'.AA13>,<Cell 'New Title'.AB13>,<Cell 'New Title'.AC13>,<Cell 'New Title'.AD13>,<Cell 'New Title'.AE13>,<Cell 'New Title'.AF13>,<Cell 'New Title'.AG13>,<Cell 'New Title'.AH13>,<Cell 'New Title'.AI13>,<Cell 'New Title'.AJ13>,...,<Cell 'New Title'.AR13>,<Cell 'New Title'.AS13>,<Cell 'New Title'.AT13>,<Cell 'New Title'.AU13>,<Cell 'New Title'.AV13>,<Cell 'New Title'.AW13>,<Cell 'New Title'.AX13>,<Cell 'New Title'.AY13>,<Cell 'New Title'.AZ13>,<Cell 'New Title'.BA13>
4,<Cell 'New Title'.AA14>,<Cell 'New Title'.AB14>,<Cell 'New Title'.AC14>,<Cell 'New Title'.AD14>,<Cell 'New Title'.AE14>,<Cell 'New Title'.AF14>,<Cell 'New Title'.AG14>,<Cell 'New Title'.AH14>,<Cell 'New Title'.AI14>,<Cell 'New Title'.AJ14>,...,<Cell 'New Title'.AR14>,<Cell 'New Title'.AS14>,<Cell 'New Title'.AT14>,<Cell 'New Title'.AU14>,<Cell 'New Title'.AV14>,<Cell 'New Title'.AW14>,<Cell 'New Title'.AX14>,<Cell 'New Title'.AY14>,<Cell 'New Title'.AZ14>,<Cell 'New Title'.BA14>
5,<Cell 'New Title'.AA15>,<Cell 'New Title'.AB15>,<Cell 'New Title'.AC15>,<Cell 'New Title'.AD15>,<Cell 'New Title'.AE15>,<Cell 'New Title'.AF15>,<Cell 'New Title'.AG15>,<Cell 'New Title'.AH15>,<Cell 'New Title'.AI15>,<Cell 'New Title'.AJ15>,...,<Cell 'New Title'.AR15>,<Cell 'New Title'.AS15>,<Cell 'New Title'.AT15>,<Cell 'New Title'.AU15>,<Cell 'New Title'.AV15>,<Cell 'New Title'.AW15>,<Cell 'New Title'.AX15>,<Cell 'New Title'.AY15>,<Cell 'New Title'.AZ15>,<Cell 'New Title'.BA15>
6,<Cell 'New Title'.AA16>,<Cell 'New Title'.AB16>,<Cell 'New Title'.AC16>,<Cell 'New Title'.AD16>,<Cell 'New Title'.AE16>,<Cell 'New Title'.AF16>,<Cell 'New Title'.AG16>,<Cell 'New Title'.AH16>,<Cell 'New Title'.AI16>,<Cell 'New Title'.AJ16>,...,<Cell 'New Title'.AR16>,<Cell 'New Title'.AS16>,<Cell 'New Title'.AT16>,<Cell 'New Title'.AU16>,<Cell 'New Title'.AV16>,<Cell 'New Title'.AW16>,<Cell 'New Title'.AX16>,<Cell 'New Title'.AY16>,<Cell 'New Title'.AZ16>,<Cell 'New Title'.BA16>
7,<Cell 'New Title'.AA17>,<Cell 'New Title'.AB17>,<Cell 'New Title'.AC17>,<Cell 'New Title'.AD17>,<Cell 'New Title'.AE17>,<Cell 'New Title'.AF17>,<Cell 'New Title'.AG17>,<Cell 'New Title'.AH17>,<Cell 'New Title'.AI17>,<Cell 'New Title'.AJ17>,...,<Cell 'New Title'.AR17>,<Cell 'New Title'.AS17>,<Cell 'New Title'.AT17>,<Cell 'New Title'.AU17>,<Cell 'New Title'.AV17>,<Cell 'New Title'.AW17>,<Cell 'New Title'.AX17>,<Cell 'New Title'.AY17>,<Cell 'New Title'.AZ17>,<Cell 'New Title'.BA17>
8,<Cell 'New Title'.AA18>,<Cell 'New Title'.AB18>,<Cell 'New Title'.AC18>,<Cell 'New Title'.AD18>,<Cell 'New Title'.AE18>,<Cell 'New Title'.AF18>,<Cell 'New Title'.AG18>,<Cell 'New Title'.AH18>,<Cell 'New Title'.AI18>,<Cell 'New Title'.AJ18>,...,<Cell 'New Title'.AR18>,<Cell 'New Title'.AS18>,<Cell 'New Title'.AT18>,<Cell 'New Title'.AU18>,<Cell 'New Title'.AV18>,<Cell 'New Title'.AW18>,<Cell 'New Title'.AX18>,<Cell 'New Title'.AY18>,<Cell 'New Title'.AZ18>,<Cell 'New Title'.BA18>
9,<Cell 'New Title'.AA19>,<Cell 'New Title'.AB19>,<Cell 'New Title'.AC19>,<Cell 'New Title'.AD19>,<Cell 'New Title'.AE19>,<Cell 'New Title'.AF19>,<Cell 'New Title'.AG19>,<Cell 'New Title'.AH19>,<Cell 'New Title'.AI19>,<Cell 'New Title'.AJ19>,...,<Cell 'New Title'.AR19>,<Cell 'New Title'.AS19>,<Cell 'New Title'.AT19>,<Cell 'New Title'.AU19>,<Cell 'New Title'.AV19>,<Cell 'New Title'.AW19>,<Cell 'New Title'.AX19>,<Cell 'New Title'.AY19>,<Cell 'New Title'.AZ19>,<Cell 'New Title'.BA19>